### ISSUE TITLE
Why do you check @Field annotation?

### ISSUE THREAD

**Issue by ngbalk** [bolcom/spring-data-mongodb-encrypt#10]
https://github.com/bolcom/spring-data-mongodb-encrypt/blob/aa72effc7aa36da5f4b0bc09db46425a099299db/src/main/java/com/bol/reflection/ReflectionCache.java#L35

Is this necessary?  @Field is not required.

**Comment by agoston** [comment]
It was added as a sanity check, mostly.

Also keep in mind that during startup, a reflection cache is built up. This would make sure that we don't start descending into references that are not planned as such.

I see no great issue removing this limit, especially since spring-data-mongo would indeed serialize any non-transient fields anyway.

**Comment by agoston** [comment]
Released 1.2.1 that removes this check.
