### ISSUE TITLE
Add ALv2 license headers to all files

### ISSUE THREAD

**Issue by atsticks** [bolcom/spring-data-mongodb-encrypt#26]
It is important (and also good practice) to add the license headers to all files (java, xml, properties etc), not only the project settings. See also the ASF guidelines. Should I do a pull request?

**Comment by agoston** [comment]
That would result in a massive amount of text added to each source file, making it harder to focus on the actual functionality. So when it can be avoided, I'd definitely opt for the cleaner way.

Turns out that this is more a recommendation than a rule, see:

https://softwareengineering.stackexchange.com/questions/270091/is-a-license-header-in-source-files-required-when-applying-the-apache-software-l

https://softwareengineering.stackexchange.com/questions/317041/should-i-add-the-license-in-every-header-and-source-file

Now of course this is hardly legal advice, but for the time being, I think it's sufficient to say that it's unnecessary.

**Comment by atsticks** [comment]
never mind. Believe it or not there is a reason that all major oss
organizations do it that way. And its about 10-15 lines per file, so
readability is not really affected. At ASF its definitivly enforced ;-).

Agoston Horvath <notifications@github.com> schrieb am Fr., 7. Feb. 2020,
14:34:
