### ISSUE TITLE
Managing keys with AWS KMS and the role of libmongocrypt

### ISSUE THREAD

**Issue by jasonenglish** [bolcom/spring-data-mongodb-encrypt#33]
Hi! I'm currently searching for ways to provide CSFLE into a new mongo database. I've been reading through a lot of documentation, official and unofficial demo repos and I have a few questions that I'm unsure about. I ran across this project and it's exactly where my thoughts were headed.

I didn't see anything in the readme with instructions on where to post questions, so I hope it's ok to post the question here.

* **Were there any considerations for using `libmongocrypt` in the projects development?**
A lot of the official documentation makes reference to the `libmongocrypt` library for assisting drivers in supporting encryption. I don't see it being referenced or used in this project and was just curious if there's any reason to go a different route.
* **Would it be possible to use a Key Management Service vs having to manually update the keys in the yaml file? Any thoughts on this?**

Thank you so much for any insight you can provide!

**Comment by agoston** [comment]
Good one! I never considered using an external library as this is a lightweight, simple library, so re-using jvm's own (likely optimal) encryption is the best.

I guess it's possible to rely on a platform-dependent library for encryption, but since encryption is also native in the jvm, I wonder what the performance would look like. It would sure add complexity to the library. If you have the time, fork it and run some measurements!

An external keystore is indeed handy, but here comes again the lightweight principle. You can easily wire a keystore of your liking into the spring config of `CryptVault`. There is no need to add native support for that. If you manage to make something nice, do publish it and I'll link it from here as a helper library. But I'd really like to keep this library lean but highly extensible, so that people from many different backgrounds can make use of it without much cruft.

**Comment by jasonenglish** [comment]
Thank you for your insights on this, it was really helpful!
