### ISSUE TITLE
Consider cleanup of com.bol.util

### ISSUE THREAD

**Issue by mp911de** [bolcom/spring-data-mongodb-encrypt#7]
Utilities currently assume behavior which is subject to change in a future version (e.g. Java 9, 10, …). Consider removing final field modification in favor of requiring a proper runtime setup.

Also, implementing a sneaky throws behavior isn't something that belongs into a library as it can cause quite some surprise during runtime.

**Comment by agoston** [comment]
Agreed on both points.

I've replaced Thrower with a properly phrased RuntimeException in release 1.1.0.

As for the crypt, since restricted mode has just been enabled in java8u162 (see https://bugs.openjdk.java.net/browse/JDK-8170157), I've deprecated it spring-data-mongodb-encrypt and changed to log a warning on failure instead of throwing an exception. I will remove it later on.

Thanks for your feedback!
